# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"add": "00_core.ipynb",
         "CountVectorizer": "01_count_vectorizer.ipynb"}

modules = ["core.py",
           "feature_extraction/text.py"]

doc_url = "https://Faizan-E-Mustafa.github.io/scratch/"

git_url = "https://github.com/Faizan-E-Mustafa/scratch/tree/master/"

def custom_doc_links(name): return None
